ACUPUNTURA
ALERGIA E IMUNOLOGIA
ANESTESIOLOGIA
ANGIOLOGIA
CANCEROLOGIA
CARDIOLOGIA
CIRURGIA CARDIOVASCULAR
CIRURGIA DE CABEÇA E PESCOÇO
CIRURGIA DO APARELHO DIGESTIVO
CIRURGIA GERAL
CIRURGIA PEDIÁTRICA
CIRURGIA PLÁSTICA
CIRURGIA TORÁCICA
CIRURGIA VASCULAR
CLÍNICA MÉDICA
COLOPROCTOLOGIA
DERMATOLOGIA
ENDOCRINOLOGIA
ENDOSCOPIA
GASTROENTEROLOGIA
GENÉTICA MÉDICA
GERIATRIA
GINECOLOGIA E OBSTETRÍCIA
HEMATOLOGIA E HEMOTERAPIA
HOMEOPATIA
INFECTOLOGIA
MASTOLOGIA
MEDICINA DE FAMÍLIA E COMUNIDADE
MEDICINA DO TRABALHO
MEDICINA DO TRÁFEGO
MEDICINA ESPORTIVA
MEDICINA FÍSICA E REABILITAÇÃO
MEDICINA INTENSIVA
MEDICINA LEGAL
MEDICINA NUCLEAR
MEDICINA PREVENTIVA E SOCIAL
NEFROLOGIA
NEUROCIRURGIA
NEUROLOGIA
NUTROLOGIA
OFTALMOLOGIA
ORTOPEDIA E TRAUMATOLOGIA
OTORRINOLARINGOLOGIA
PATOLOGIA
PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL
PEDIATRIA
PNEUMOLOGIA
PSIQUIATRIA
RADIOLOGIA E DIAGNÓSTICO POR IMAGEM
RADIOTERAPIA
REUMATOLOGIA
UROLOGIA