DROP TRIGGER IF EXISTS `plus_saldo`;
DELIMITER //
CREATE TRIGGER `plus_saldo` AFTER INSERT ON `endereco`
 FOR EACH ROW BEGIN
UPDATE saldo
   SET valor = valor + 10
 WHERE COD_USUARIO = NEW.COD_USUARIO;

END
//
DELIMITER ;

ALTER TABLE  `pedido` ADD  `MODO_ENTREGA` TINYINT NOT NULL DEFAULT  '1' AFTER  `COD_LIVRO`

CREATE TABLE `chat` (
 `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
 `COD_PEDIDO` int(11) NOT NULL,
 `COD_USUARIO` int(11) NOT NULL,
 `COD_USUARIO_PARA` int(11) NOT NULL,
 `MENSAGEM` text COLLATE utf8_unicode_ci NOT NULL,
 `DATA_HORA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

CREATE ALGORITHM = UNDEFINED VIEW  `v_chat` AS SELECT chat.CODIGO, chat.MENSAGEM, chat.DATA_HORA, chat.COD_PEDIDO, pedido.COD_USUARIO_DE, pedido.COD_USUARIO_PARA
FROM  `chat` 
JOIN pedido ON chat.COD_PEDIDO = pedido.CODIGO

