RENAME TABLE  `tcc`.`qualiusuario` TO  `tcc`.`qualificacao` ;
RENAME TABLE  `tcc`.`minhabiblio` TO  `tcc`.`estantevirtual` ;
RENAME TABLE  `tcc`.`financas` TO  `tcc`.`saldo` ;
ALTER TABLE  `estantevirtual` ADD  `ESCOPO` TINYINT NOT NULL DEFAULT  '1' COMMENT  '1=DISPONIVEL, 0=INDISPONIVEL,2=TRANSICAO' AFTER  `STATUS` ;
ALTER TABLE  `estantevirtual` CHANGE  `STATUS`  `STATUS` TINYINT( 4 ) NOT NULL COMMENT  '0:NAO_LIDO, 1:LIDO, 2:LENDO';

ALTER TABLE  `pedido` ADD  `STATUS` TINYINT NOT NULL DEFAULT  '1' COMMENT  '0=RECUSADO, 1=AGUARDANDO, 2=ACEITO',
ADD  `DATA_PEDIDO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
ADD  `DATA_ACEITACAO` DATETIME NOT NULL ;

ALTER TABLE  `qualificacao` CHANGE  `TITULO`  `TITULO` TINYINT NOT NULL COMMENT  '0=pessimo,1=Ruim,2= Regular,3= Bom, 4=Otimo';
ALTER TABLE  `pedido` CHANGE  `COD_USUARIO_DE`  `COD_USUARIO_DE` INT( 11 ) NULL DEFAULT NULL ;
ALTER TABLE  `pedido` CHANGE  `DATA_ACEITACAO`  `DATA_ACEITACAO` DATETIME NULL DEFAULT NULL ;

