DROP TRIGGER IF EXISTS `plus_saldo`;
DELIMITER //
CREATE TRIGGER `plus_saldo` AFTER INSERT ON `endereco`
 FOR EACH ROW BEGIN
UPDATE saldo
   SET valor = 10
 WHERE COD_USUARIO = NEW.COD_USUARIO;

END
//
DELIMITER ;